import type { HistoricalMapDefinition } from '../schema.ts'

export const shandongManchuria1927To1928Map: HistoricalMapDefinition = {
  id:'shandong-manchuria-1927-1928',
  title:'1927〜1928年の山東・華北・南満洲の政治／軍事空間（模式）',
  historicalQuestion:
    '北伐の北上、山東出兵、南満洲鉄道沿線、奉天での張作霖爆殺事件は、どのように異なる空間と権限の上で同時進行したのか。',
  readingNote:
    '北伐の線は南京―済南―北京という政治・軍事的な北上方向を示す模式線、南満洲鉄道の線は大連―奉天―長春の主要接続を示す模式回廊で、実際の部隊進路や鉄道中心線ではない。関東州の租借地境界は法的境界の誤認を避けるため面として描かず、大連・旅順を代表点で示す。背景地図・国境・道路は現代のOpenStreetMapである。',
  status:'draft',
  period:{startYear:1927,endYear:1928},
  initialView:{center:[120.8,37.8],zoom:4.05},
  datasets:[
    {
      id:'a15-points',
      provenance:{
        sourceId:'a15-official-reference-points',
        title:'山東出兵・張作霖爆殺事件・南満洲鉄道関係の主要地点',
        institution:'国立国会図書館・防衛省防衛研究所',
        url:'https://ndlsearch.ndl.go.jp/rnavi/db/cabinet/s2_8/bib00002',
        sourceType:'derived',
        license:'Site-authored approximate representative coordinates based on official/research historical descriptions; no historical boundary geometry is copied.',
        derivedFromSourceIds:['ndl-shandong-cabinet-1927','nids-zhang-assassination','smr-historical-context'],
        temporalCoverage:{from:'1927-05-01',to:'1928-06-30',basis:'range'},
        spatialCoverage:'南京・山東・北京から大連・奉天・長春',
        geometryConfidence:'approximate',
        transformations:[
          '閣議決定・防衛研究所研究で山東出兵、済南、奉天近郊の事件を確認した。',
          '主要都市・港・事件地点を現在の同名地域付近の代表座標へ配置した。',
          '租借地境界・鉄道附属地境界・軍の展開範囲は復元していない。',
        ],
        notes:'政治中心、軍事衝突地点、鉄道権益の拠点を区別して読むための代表点。',
      },
      allowedGeometryTypes:['Point'],
      requiredProperties:['category','marker','label','labelPlacement','year','detail'],
      features:[
        {id:'a15-nanjing',geometry:{type:'Point',coordinates:[118.80,32.06]},properties:{category:'northern-expedition-node',marker:'北',label:'南京',labelPlacement:'bottom',year:'1927–1928',detail:'国民政府の政治中心。北伐の北上方向を読む南側の基準点。'}},
        {id:'a15-jinan',geometry:{type:'Point',coordinates:[117.12,36.65]},properties:{category:'conflict-node',marker:'戦',label:'済南',labelPlacement:'right',year:'1928',detail:'山東出兵と北伐軍が交差し、1928年に武力衝突が起きた主要都市。'}},
        {id:'a15-beijing',geometry:{type:'Point',coordinates:[116.41,39.90]},properties:{category:'northern-expedition-node',marker:'北',label:'北京',labelPlacement:'left',year:'1928',detail:'北伐の北上を理解する華北側の主要政治中心。'}},
        {id:'a15-dalian',geometry:{type:'Point',coordinates:[121.62,38.92]},properties:{category:'leased-port-node',marker:'租',label:'大連',labelPlacement:'right',year:'1927–1928',detail:'関東州と南満洲鉄道の海港側拠点。租借地境界そのものはこの地図では描かない。'}},
        {id:'a15-portarthur',geometry:{type:'Point',coordinates:[121.26,38.81]},properties:{category:'leased-port-node',marker:'租',label:'旅順',labelPlacement:'left',year:'1927–1928',detail:'関東州の主要軍港・行政参照地点。'}},
        {id:'a15-mukden',geometry:{type:'Point',coordinates:[123.43,41.80]},properties:{category:'railway-node',marker:'鉄',label:'奉天',labelPlacement:'right',year:'1927–1928',detail:'南満洲鉄道沿線の主要都市。張作霖政権の拠点でもあった。'}},
        {id:'a15-huanggutun',geometry:{type:'Point',coordinates:[123.39,41.84]},properties:{category:'incident-node',marker:'事',label:'皇姑屯付近',labelPlacement:'left',year:'1928-06-04',detail:'張作霖爆殺事件が起きた奉天近郊の鉄道地点を概略位置で示す。'}},
        {id:'a15-changchun',geometry:{type:'Point',coordinates:[125.32,43.90]},properties:{category:'railway-node',marker:'鉄',label:'長春',labelPlacement:'right',year:'1927–1928',detail:'南満洲鉄道北側の主要接続都市。'}},
      ],
    },
    {
      id:'a15-lines',
      provenance:{
        sourceId:'a15-schematic-corridors',
        title:'北伐北上方向・南満洲鉄道主要回廊（模式）',
        institution:'jpn-history-decade',
        url:'https://www.nids.mod.go.jp/publication/senshi/pdf/200303/11.pdf',
        sourceType:'derived',
        license:'Site-authored schematic LineStrings based on documented political/military direction and railway endpoint relationships; no historical route vector is copied.',
        derivedFromSourceIds:['ndl-shandong-cabinet-1927','nids-zhang-assassination','smr-historical-context'],
        temporalCoverage:{from:'1927-05-01',to:'1928-06-30',basis:'range'},
        spatialCoverage:'南京―済南―北京、大連―奉天―長春',
        geometryConfidence:'schematic',
        transformations:[
          '北伐が南京から華北へ北上し、山東・済南が日本の出兵対象となった政治・軍事文脈を確認した。',
          '南満洲鉄道の主要接続を大連・奉天・長春の代表waypointで模式化した。',
          '北伐軍の実進路、山東出兵部隊の展開線、鉄道中心線、附属地境界は作成していない。',
        ],
        notes:'二種類の線は意味が異なるため凡例を分離する。',
      },
      allowedGeometryTypes:['LineString'],
      requiredProperties:['category','label','detail'],
      features:[
        {id:'a15-northern-expedition-axis',geometry:{type:'LineString',coordinates:[[118.80,32.06],[117.12,36.65],[116.41,39.90]]},properties:{category:'northern-expedition-axis',label:'北伐の北上方向（模式）',detail:'南京から山東・華北へ北上した政治・軍事的方向を示す。実際の部隊進路ではない。'}},
        {id:'a15-smr-corridor',geometry:{type:'LineString',coordinates:[[121.62,38.92],[122.99,41.10],[123.43,41.80],[125.32,43.90]]},properties:{category:'smr-corridor',label:'南満洲鉄道主要回廊（模式）',detail:'大連から奉天・長春へ伸びる主要接続を示す模式線。正確な線路中心線ではない。'}},
      ],
    },
  ],
  layers:[
    {id:'a15-lines-layer',datasetId:'a15-lines',categoryProperty:'category',categories:['northern-expedition-axis','smr-corridor']},
    {id:'a15-points-layer',datasetId:'a15-points',categoryProperty:'category',categories:['northern-expedition-node','conflict-node','leased-port-node','railway-node','incident-node']},
  ],
  legend:[
    {value:'northern-expedition-axis',label:'北伐の北上方向（模式）',marker:'線',color:'#7b4d3d',kind:'line',lineStyle:'dashed'},
    {value:'smr-corridor',label:'南満洲鉄道主要回廊（模式）',marker:'線',color:'#4d5f70',kind:'line',lineStyle:'dashed'},
    {value:'northern-expedition-node',label:'北伐・国民政府側の主要政治地点',marker:'北',color:'#6c563a'},
    {value:'conflict-node',label:'山東の主要軍事衝突地点',marker:'戦',color:'#823f35'},
    {value:'leased-port-node',label:'関東州の主要参照地点（境界は非表示）',marker:'租',color:'#67577a'},
    {value:'railway-node',label:'南満洲鉄道の主要接続都市',marker:'鉄',color:'#3f5d6e'},
    {value:'incident-node',label:'張作霖爆殺事件地点（概略）',marker:'事',color:'#7a4939'},
  ],
  auditState:{
    dataAudit:'passed',
    styleAudit:'passed',
    visualAudit:'pending-human',
    notes:[
      'A15は旧判定で北伐進路・満鉄線・関東州境界を同一精度で作れないためno-mapだったが、法的境界を描かず、異なる意味の線・点を別レイヤーに分ければ中心問いを表現できると再判定した。',
      '関東州polygonは法的境界の誤認を避けるため引き続き不採用。',
      'LineStringを含むためHuman Visual Auditは後送する。',
    ],
  },
}
