import type { HistoricalMapDefinition } from '../schema.ts'

export const urbanPopulation1920Map: HistoricalMapDefinition = {
  id: 'urban-population-1920',
  title: '1920年国勢調査：人口10万人以上の市・区',
  historicalQuestion:
    '第1回国勢調査が捉えた大都市人口は、東京・大阪だけでなく日本列島のどこに分布していたのか。',
  readingNote:
    '人口は1920年国勢調査の当時の市・区単位。点は都市の代表位置を現在の地理上へ概略配置したもので、1920年の市域・区界を示さない。札幌は当時「札幌区」。背景地図・海岸線は現代のOpenStreetMapであり、歴史境界ではない。',
  status: 'published',
  period: { startYear: 1920, endYear: 1920 },
  initialView: {
    center: [136.9, 36.6],
    zoom: 3.8,
  },
  datasets: [
    {
      id: 'urban-population-points-1920',
      provenance: {
        sourceId: 'stats-first-census-1920',
        title: '大正9年（1920年）第1回国勢調査 市・区人口から作成した都市代表点',
        institution: 'jpn-history-decade',
        sourceType: 'derived',
        license:
          'Population values derived from official Statistics Bureau census tables. Coordinates are site-authored approximate representative points; no historical boundary geometry copied.',
        derivedFromSourceIds: ['stats-first-census-1920'],
        temporalCoverage: {
          from: '1920-10-01',
          to: '1920-10-01',
          basis: 'instant',
          note: '第1回国勢調査の調査時点。人口10万人以上の市・区を対象とする。',
        },
        spatialCoverage: '1920年国勢調査で人口10万人以上だった日本内地の市・区',
        geometryConfidence: 'approximate',
        transformations: [
          '1920年国勢調査の当時自治体別人口から人口10万人以上の市・区を抽出した。',
          '人口規模を4区分（100万人以上、40万〜100万人未満、15万〜40万人未満、10万〜15万人未満）へ分類した。',
          '歴史的市域ポリゴンは作成せず、各都市名を現在の地理上の代表点へ概略配置した。',
        ],
        notes:
          '人口値の比較が主題であり、点位置は都市のおおよその位置関係を示す。面積・人口密度・1920年市域の分析には使用しない。',
      },
      allowedGeometryTypes: ['Point'],
      requiredProperties: [
        'category',
        'marker',
        'label',
        'labelPlacement',
        'year',
        'population',
        'detail',
      ],
      features: [
        {
          id: 'tokyo-1920',
          geometry: { type: 'Point', coordinates: [139.76, 35.68] },
          properties: {
            category: 'million-plus',
            marker: '●',
            label: '東京市',
            labelPlacement: 'top',
            year: 1920,
            population: 2173162,
            detail: '人口 2,173,162人。1920年時点の東京市人口で、後年の市域拡張前の値。',
          },
        },
        {
          id: 'osaka-1920',
          geometry: { type: 'Point', coordinates: [135.50, 34.69] },
          properties: {
            category: 'million-plus',
            marker: '●',
            label: '大阪市',
            labelPlacement: 'left',
            year: 1920,
            population: 1252972,
            detail: '人口 1,252,972人。1920年時点で100万人を超えた二大都市の一つ。',
          },
        },
        {
          id: 'kobe-1920',
          geometry: { type: 'Point', coordinates: [135.19, 34.69] },
          properties: {
            category: 'large',
            marker: '◆',
            label: '神戸市',
            labelPlacement: 'bottom',
            year: 1920,
            population: 608628,
            detail: '人口 608,628人。港湾都市として大都市人口を形成した。',
          },
        },
        {
          id: 'kyoto-1920',
          geometry: { type: 'Point', coordinates: [135.76, 35.01] },
          properties: {
            category: 'large',
            marker: '◆',
            label: '京都市',
            labelPlacement: 'top',
            year: 1920,
            population: 591305,
            detail: '人口 591,305人。',
          },
        },
        {
          id: 'nagoya-1920',
          geometry: { type: 'Point', coordinates: [136.91, 35.18] },
          properties: {
            category: 'large',
            marker: '◆',
            label: '名古屋市',
            labelPlacement: 'right',
            year: 1920,
            population: 429990,
            detail: '人口 429,990人。',
          },
        },
        {
          id: 'yokohama-1920',
          geometry: { type: 'Point', coordinates: [139.64, 35.45] },
          properties: {
            category: 'large',
            marker: '◆',
            label: '横浜市',
            labelPlacement: 'bottom',
            year: 1920,
            population: 422942,
            detail: '人口 422,942人。東京に近接する港湾都市として大都市人口を形成した。',
          },
        },
        {
          id: 'nagasaki-1920',
          geometry: { type: 'Point', coordinates: [129.87, 32.75] },
          properties: {
            category: 'middle',
            marker: '■',
            label: '長崎市',
            labelPlacement: 'right',
            year: 1920,
            population: 176554,
            detail: '人口 176,554人。',
          },
        },
        {
          id: 'hiroshima-1920',
          geometry: { type: 'Point', coordinates: [132.46, 34.40] },
          properties: {
            category: 'middle',
            marker: '■',
            label: '広島市',
            labelPlacement: 'right',
            year: 1920,
            population: 160504,
            detail: '人口 160,504人。',
          },
        },
        {
          id: 'hakodate-1920',
          geometry: { type: 'Point', coordinates: [140.73, 41.77] },
          properties: {
            category: 'hundred-thousand',
            marker: '○',
            label: '函館市',
            labelPlacement: 'right',
            year: 1920,
            population: 144740,
            detail: '人口 144,740人。',
          },
        },
        {
          id: 'kure-1920',
          geometry: { type: 'Point', coordinates: [132.57, 34.25] },
          properties: {
            category: 'hundred-thousand',
            marker: '○',
            label: '呉市',
            labelPlacement: 'bottom',
            year: 1920,
            population: 130354,
            detail: '人口 130,354人。広島市に近接する軍港・工業都市。',
          },
        },
        {
          id: 'kanazawa-1920',
          geometry: { type: 'Point', coordinates: [136.66, 36.56] },
          properties: {
            category: 'hundred-thousand',
            marker: '○',
            label: '金沢市',
            labelPlacement: 'right',
            year: 1920,
            population: 129320,
            detail: '人口 129,320人。',
          },
        },
        {
          id: 'sendai-1920',
          geometry: { type: 'Point', coordinates: [140.87, 38.27] },
          properties: {
            category: 'hundred-thousand',
            marker: '○',
            label: '仙台市',
            labelPlacement: 'right',
            year: 1920,
            population: 118978,
            detail: '人口 118,978人。',
          },
        },
        {
          id: 'otaru-1920',
          geometry: { type: 'Point', coordinates: [141.00, 43.19] },
          properties: {
            category: 'hundred-thousand',
            marker: '○',
            label: '小樽市',
            labelPlacement: 'left',
            year: 1920,
            population: 108113,
            detail: '人口 108,113人。北海道の港湾・商業都市。',
          },
        },
        {
          id: 'sapporo-ku-1920',
          geometry: { type: 'Point', coordinates: [141.35, 43.06] },
          properties: {
            category: 'hundred-thousand',
            marker: '○',
            label: '札幌区',
            labelPlacement: 'bottom',
            year: 1920,
            population: 102571,
            detail: '人口 102,571人。1920年国勢調査時点では「札幌区」で、札幌市への移行は1922年。',
          },
        },
        {
          id: 'kagoshima-1920',
          geometry: { type: 'Point', coordinates: [130.56, 31.60] },
          properties: {
            category: 'hundred-thousand',
            marker: '○',
            label: '鹿児島市',
            labelPlacement: 'right',
            year: 1920,
            population: 102396,
            detail: '人口 102,396人。',
          },
        },
        {
          id: 'yahata-1920',
          geometry: { type: 'Point', coordinates: [130.80, 33.87] },
          properties: {
            category: 'hundred-thousand',
            marker: '○',
            label: '八幡市',
            labelPlacement: 'left',
            year: 1920,
            population: 100227,
            detail: '人口 100,227人。官営八幡製鉄所を核に成長した工業都市。',
          },
        },
      ],
    },
  ],
  layers: [
    {
      id: 'urban-population-points-1920',
      datasetId: 'urban-population-points-1920',
      categoryProperty: 'category',
      categories: ['million-plus', 'large', 'middle', 'hundred-thousand'],
    },
  ],
  legend: [
    { value: 'million-plus', label: '100万人以上', marker: '●', color: '#5f4030' },
    { value: 'large', label: '40万〜100万人未満', marker: '◆', color: '#365d70' },
    { value: 'middle', label: '15万〜40万人未満', marker: '■', color: '#69602e' },
    { value: 'hundred-thousand', label: '10万〜15万人未満', marker: '○', color: '#55624b' },
  ],
  auditState: {
    dataAudit: 'passed',
    styleAudit: 'passed',
    visualAudit: 'passed',
    notes: [
      '人口値は1920年国勢調査の当時自治体単位を使用し、現代自治体へ組替えていない。',
      '歴史的市域境界を使用せず、代表点のみを概略配置したため geometryConfidence=approximate とした。',
      '人口規模は色だけでなく記号形状でも区別し、地点名を初期表示する。',
      '2026-09-27にGitHub Pages上の実表示をHuman Visual Auditし、地図の見た目は承認済み。',
    ],
  },
}
